### ISSUE TITLE
No test matches the given testcase filter

### ISSUE THREAD

**Issue by jing8956** [TimorCms/Timor.Cms#13]
我看到 Timor.Cms.Repository.MongoDb.IntegrationTests 测试没有在 CI 上运行？
![image](https://user-images.githubusercontent.com/20148769/79415674-92c4e300-7fe0-11ea-8e24-6f4de8b43282.png)

**Comment by baiyunchen** [comment]
是的，因为目前没有MongoDb的线上环境，所以集成测试只能在本地跑，暂时跳过了CI中集成测试的执行。
