### ISSUE TITLE
更新分类API

### ISSUE THREAD

**Issue by jing8956** [TimorCms/Timor.Cms#14]
### 更新全部字段
PUT api/v1/categories/{id}
#### 参数：
```javascript
{
  Name:             "string" //分类名称
  Description:      "string" //分类描述
  Priority:         0        //优先级
  ParentCategoryId: "string" //父分类ID
}
```
#### 返回：
HTTP 204 NOCONTENT

**Comment by baiyunchen** [comment]
1.不需要更新部分字段的API
2.参数使用JSON的形式表示出来
3.缺少Response的部分

**Comment by baiyunchen** [comment]
@jing8956 请调整JSON文本格式，尽量美观一些。
另外，对于创建成功，只需要返回一个获取该资源的uri即可。
